---
title: "FML ASSIGNMENT 1-811290653"
output:
  html_document:
    df_print: paged
  pdf_document: default
date: "2023-09-08"
 
---
#part 1 **- importing the data 


#The Source of the Data set :https://www.kaggle.com/datasets/fiq423ubf/cbse-result-statistics-class-xii-2023

```{r}
a<-read.csv("C:/Users/geeth/OneDrive/Desktop/class12-2023 (1).csv")

a

```
#part 2 **-descriptive statistics for quantitative variables
```{r}
summary(a)

mean(a$KV)

median(a$KV)

sum(a$KV)

sd(a$KV)

var(a$KV)

max(a$KV)

min(a$KV)

str(a$KV)
```
#part 3 **- descriptive statistics for categorical variables

```{r}
table(a$Status)

a$Status

table(a$Region)

str(a$Status)
```

#part 4 - transforming the variables
```{r}
log(a$KV)

log(a$CTSA)

 b<-a$INDEPENDENT-mean(a$INDEPENDENT)/sd(a$INDEPENDENT)
 
 b
```
#part 5 - plotting the one variables

```{r}
hist(a$KV,main="HISTOGRAM OF KV")
```

#part 6- scatterplot
```{r}
plot(a$KV,a$JNV,main="scatterplot")
```


``

